### ISSUE TITLE
pact_broker-client v1.36.0 , published the pacts to the broker Failed

### ISSUE THREAD

**Issue by stephenwang1011** [pact-foundation/pact_broker-client#80]
Hi team, I run the publishing  the pacts to broker job in the circleCI flow, when I updated the pact_broker-client to 1.36.0, publishing the pacts to the broker failed, here is the log:

```
#!/bin/bash -eo pipefail
pact-broker publish ./Pacts --consumer-app-version=${CIRCLE_SHA1} --tag=${CIRCLE_BRANCH} --broker-base-url=${PACT_BROKER_URL} --broker-username=${PACT_BROKER_USERNAME} --broker-password=${PACT_BROKER_PASSWORD} -v
/opt/circleci/.rvm/gems/ruby-2.3.1/gems/pact_broker-client-1.36.0/lib/pact_broker/client/cli/broker.rb:224:in `publish_pacts': undefined method `compact' for #<Hash:0x00000003ae50d0> (NoMethodError)
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pact_broker-client-1.36.0/lib/pact_broker/client/cli/broker.rb:64:in `publish'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pact_broker-client-1.36.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/gems/pact_broker-client-1.36.0/bin/pact-broker:4:in `<top (required)>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/pact-broker:23:in `load'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/pact-broker:23:in `<main>'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /opt/circleci/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Exited with code exit status 1
CircleCI received exit code 1
```

And this is my publish command:

`pact-broker publish ./Pacts --consumer-app-version=${CIRCLE_SHA1} --tag=${CIRCLE_BRANCH} --broker-base-url=${PACT_BROKER_URL} --broker-username=${PACT_BROKER_USERNAME} --broker-password=${PACT_BROKER_PASSWORD} -v
`

It worked fine when I downgrade to **v1.35.0.**
Any Suggestions?  Thanks team!

**Comment by bethesque** [comment]
Ah, good old Ruby 2.3. I've put out a fix. Please upgrade to the latest version.

**Comment by suadev** [comment]
@bethesque hi, I installed the latest pact release - >( https://github.com/pact-foundation/pact-ruby-standalone/releases ) 

it has ruby 2.2.0 inside of it. I installed the latest 3.0.0 ruby version. ( https://rubyinstaller.org/downloads ) 

But it doesn't work, is there a pact release that has the latest ruby version?

**Comment by suadev** [comment]
@stephenwang1011 do you have any idea about my question?

**Comment by bethesque** [comment]
The standalone uses its own version of Ruby - you can't change that. Unfortunately, we're stuck on an old version of Ruby because Travelling Ruby, which we use to create the standalone, is not actively maintained any more. The plan is to move away from that to a shared Rust core. See https://docs.pact.io/history/

**Comment by bethesque** [comment]
I've updated the pact broker client to not use the code that caused the bug. If you grab the latest version of which ever package you're using, it should be working again.

**Comment by suadev** [comment]
@bethesque it worked, thank you!
